### ISSUE TITLE
Move default template names to config

### ISSUE THREAD

**Issue by mvar** [ongr-io/CurrencyExchangeBundle#32]
https://github.com/ongr-io/CurrencyExchangeBundle/blob/525b4c1c1ea150c3a33741c5400ad2b23580d4a3/Twig/PriceExtension.php#L206
https://github.com/ongr-io/CurrencyExchangeBundle/blob/525b4c1c1ea150c3a33741c5400ad2b23580d4a3/Twig/PriceExtension.php#L234

We should move defaults to config. Leave possibility to set template directly to filter.

**Comment by mvar** [comment]
Also move parameters from `services.yml` to config.

**Comment by saimaz** [comment]
@einorler please rebase your PR
